[versions]
# Define the dependency versions
kotlin = "1.7.20"
compose = "1.3.0"
composeTesting = "1.1.1"
composeActivity = "1.4.0"
composeLifecycleViewModel = "2.4.1"
accompanist = "0.26.0-alpha"
constraintLayoutCompose = "1.0.0-beta02"
retrofit = "2.9.0"
okhttpLoggingInterceptor = "4.7.0"
hilt = "2.42"
hiltNavigation = "1.0.0"
lifecycle = "2.5.1"

kotlinTestJUnit = "1.3.72"
testJUnit = "1.1.3"
espresso = "3.4.0"

[libraries]
# Define the libraries
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeAnimation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
composeTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
composeToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
composeIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
composeSystemUIController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
composeConstraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayoutCompose" }
composeViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeLifecycleViewModel" }
testing = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeTesting" }
#square up
converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okHTTPLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLoggingInterceptor" }

#Hilt
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hiltNavigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }

#Android X
lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

#Testing
testJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinTestJUnit" }
extJUnit = { module = "androidx.test.ext:junit", version.ref = "testJUnit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[bundles]
# Define bundles/groups of libraries
compose = ["composeUi", "composeMaterial", "composeTooling", "composeToolingPreview", "composeIcons", "composeActivity", "composeSystemUIController", "composeConstraintLayout", "composeAnimation"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version = "kotlin" }